version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_DATABASE}"
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
networks:
  default:
    driver: bridge
